name: Swift CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: macos-26
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Lint
        run: swiftlint lint

      - name: Build
        run: swift build -c release
